# Statistical Learning

### Loading Libraries

In [1]:
# Numerical Computing
import numpy as np

# Data Manipulation
import pandas as pd

# Data Visualization
import seaborn as sns
import matplotlib.pyplot as plt


#### Basic Commands

In [2]:
print('fit a model with ', 11, 'variables ')

fit a model with  11 variables 


In [3]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [4]:
3 + 5

8

In [5]:
"hello" + " " + "world"

'hello world'

In [6]:
x = [3, 4, 5]

x

[3, 4, 5]

In [7]:
y = [4, 9, 7]

x + y

[3, 4, 5, 4, 9, 7]

### Introduction to Numerical Python

In [8]:
x = np.array ([3, 4, 5])

y = np.array ([4, 9, 7])

In [9]:
x + y

array([ 7, 13, 12])

In [10]:
x = np.array ([[1 , 2], [3, 4]])

x

array([[1, 2],
       [3, 4]])

In [11]:
x.ndim

2

In [12]:
x.dtype

dtype('int64')

In [13]:
np.array ([[1 , 2], [3.0 , 4]]).dtype

dtype('float64')

In [14]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [15]:
np.array ([[1 , 2], [3, 4]], float).dtype

dtype('float64')

In [16]:
x.shape

(2, 2)

In [18]:
x = np.array ([1, 2, 3, 4])

x.sum ()

10

In [19]:
x = np.array ([1, 2, 3, 4])

np.sum(x)

10

In [21]:
x = np.array ([1, 2, 3, 4, 5, 6])
print('Beginning x:\n', x)

x_reshape = x.reshape ((2, 3))
print('Reshaped x:\n', x_reshape )

Beginning x:
 [1 2 3 4 5 6]
Reshaped x:
 [[1 2 3]
 [4 5 6]]


In [22]:
x_reshape [0, 0]

1

In [23]:
x_reshape [1, 2]

6

In [24]:
print('x before we modify x_reshape :\n', x)

print('x_reshape before we modify x_reshape :\n', x_reshape )

x_reshape [0, 0] = 5
print('x_reshape after we modify its top left element :\n',
x_reshape )
print('x after we modify top left element of x_reshape :\n', x)

x before we modify x_reshape :
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape :
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element :
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape :
 [5 2 3 4 5 6]


In [25]:
my_tuple = (3, 4, 5)

my_tuple [0] = 2

TypeError: 'tuple' object does not support item assignment

In [26]:
x_reshape .shape , x_reshape .ndim , x_reshape .T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [27]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [28]:
x**2

array([25,  4,  9, 16, 25, 36])

In [29]:
x**0.5

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [30]:
x = np.random.normal(size =50)
x

array([ 0.73939112,  0.31990821,  1.0452597 ,  0.59408753, -0.56938024,
       -0.01693407, -1.4018627 ,  0.0343844 , -0.78027955, -0.36909794,
        1.32938918,  0.84867102, -1.41379198, -2.04951116,  0.49869849,
        0.70040254,  0.96601724,  0.51706235, -0.26248351,  0.40005085,
        0.65324122, -0.51669978,  1.05382175,  1.68317973,  1.03279786,
       -0.2497097 , -0.21639313,  0.23550462,  0.68650806, -1.06993505,
        0.44724728, -1.41832025,  1.80372027, -0.07138455, -0.92946706,
       -0.18523545, -2.50213582, -0.52340604, -1.70995618,  0.65190239,
       -0.1728972 , -0.74166563,  1.08058499, -0.53681341, -1.39689019,
       -1.69178658,  1.9856477 , -0.42139446,  0.78687254,  0.39377201])

In [31]:
y = x + np.random.normal(loc =50, scale =1, size =50)

In [32]:
np. corrcoef (x, y)

array([[1.        , 0.69272915],
       [0.69272915, 1.        ]])

In [33]:
print(np.random.normal(scale =5, size =2))
print(np.random.normal(scale =5, size =2))

[-5.73678562 -5.18293185]
[-3.40911623  1.96230908]


In [34]:
rng = np.random. default_rng (1303)
print(rng.normal(scale =5, size =2))

rng2 = np.random. default_rng (1303)
print(rng2.normal(scale =5, size =2))

[ 4.09482632 -1.07485605]
[ 4.09482632 -1.07485605]


In [35]:
rng = np.random. default_rng (3)
y = rng. standard_normal (10)
np.mean(y), y.mean ()

(-0.1126795190952861, -0.1126795190952861)

In [36]:
np.var(y), y.var (), np.mean ((y - y.mean ())**2)

(2.7243406406465125, 2.7243406406465125, 2.7243406406465125)

In [37]:
np.sqrt(np.var(y)), np.std(y)

(1.6505576756498128, 1.6505576756498128)

In [38]:
X = rng. standard_normal ((10 , 3))
X

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])

In [39]:
X.mean(axis =0)

array([ 0.15030588,  0.14030961, -0.34238602])

In [40]:
X.mean (0)

array([ 0.15030588,  0.14030961, -0.34238602])

### `Graphics`